2024-08-19 11:19:58,427	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2024-08-19 11:19:58,753	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2024-08-19 11:19:58,753	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-19 11:19:58,753	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2024-08-19 11:19:58,753	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2024-08-19 11:19:58,806	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2024-08-19 11:19:58,887	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「推广限制-测试中」启动成功！
2024-08-19 11:19:58,887	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2024-08-19 11:21:59,769	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2024-08-19 11:21:59,954	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/users/@me, 错误代码: 401, 返回内容: {'message': 'Token错误', 'code': 11243, 'err_code': 40012002, 'trace_id': '1777009755ec067c50cc2fd3bee1cd40'}, trace_id:1777009755ec067c50cc2fd3bee1cd40
2024-08-19 11:22:39,420	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2024-08-19 11:22:39,808	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2024-08-19 11:22:39,808	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2024-08-19 11:22:39,808	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2024-08-19 11:22:39,808	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2024-08-19 11:22:39,869	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2024-08-19 11:22:39,958	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「推广限制-测试中」启动成功！
2024-08-19 11:22:39,959	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
